name: quick_blue_windows
description: Windows implementation of the quick_blue plugin.
version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: QuickBlueWindowsPlugin